### ISSUE TITLE
what all parameters we need to put to run selenium tests from xl-release

### ISSUE THREAD

**Issue by sukanta12345** [xebialabs-community/xlr-selenium-plugin#1]
what all parameters we need to put to run selenium tests from xl-release
![seleniumtest](https://user-images.githubusercontent.com/24559769/32831582-cbcaadd0-ca1e-11e7-9500-ff50be2fbaad.JPG)
. 
Server * 
Script * 
webDriver Hub URL * 
Web Browser * 
we tried with some parameter. but we are getting this error message Exception during execution: ImportError: No module named common in <script> at line number 1 
Please find the attached screenshot. Please look into it also could you please provide us the sample parameter

**Comment by vlussenburg** [comment]
Hi.

Please see updated plugin and documentation. Thanks

Vincent.
